import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/Header'
import Providers from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Online Market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="px-28">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
